version: '3.6'
services:
    nginx:
        build: docker/nginx
        restart: always
        ports:
            - "${PORT-80}:80"
        volumes:
            - './:/usr/share/nginx/html'
        depends_on:
            - database
    php-fpm:
        build: docker/php
        restart: always
        volumes:
            - './:/usr/share/nginx/html'
        depends_on:
            - database

    database:
        image: 'postgres:12'
        restart: always
        volumes:
            - pgsql-data:/var/lib/postgresql/data
        expose:
            - '5432'
        ports:
            - "5432:5432"
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
    pgsql-data:
