name: "Suggestion"
description: "Suggest an idea for Azuriom"
title: "Suggestion: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: "Use this template only if you want a new feature for Azuriom."
- type: dropdown
  id: concerned
  attributes:
    label: "What is concerned ?"
    multiple: true
    options:
    - Users
    - Plugins
    - Themes
    - Security
    - Others
- type: checkboxes
  id: versions
  attributes:
    label: "Are you using v1.x ?"
    options:
      - label: "Yes"
- type: textarea
  id: describe
  attributes:
    label: "What is your idea ? What do you want ?"
    description: "Explain your idea with screenshoots, example etc"
    placeholder: "Explain your idea !"
  validations:
    required: true
- type: textarea
  id: why
  attributes:
    label: "Why this idea ? Why it should be accepted ?"
    description: "What is the advantage of your suggestion ?"
